### ISSUE TITLE
Body parsing event

### ISSUE THREAD

**Issue by serayuzgur** [seankerr/rust-http-box#1]
Can you please provide an example which parses body on a PUT/POST request?
I can't find how to do it. None of them prints anything.
Note: I am using it with tokio-proto
```rust

  fn on_multipart_data(&mut self, data: &[u8]) -> bool {
        println!("!!!on_multipart_data");
        true
    }

    fn on_body_finished(&mut self) -> bool {
        println!("!!!on_body_finished");
        true
    }
    fn on_chunk_begin(&mut self) -> bool {
        println!("!!!on_chunk_begin ");
        true
    }
    fn on_chunk_data(&mut self, data: &[u8]) -> bool {
        println!("!!!on_chunk_data ");
        true
    }
    fn on_multipart_begin(&mut self) -> bool {
        println!("!!!on_multipart_begin ");
        true
    }
```

**Comment by seankerr** [comment]
No worries, PUT/POST are pretty easy to handle. Depending on the form encoding, it will use the chunked transfer encoding handlers, URL encoded handlers, or multipart handlers.

1) Check Content-Type header

Check the `content-type` header. For file uploads, this format is always the one that is used. It looks something like so (for file uploads): Content-Type: multipart/form-data; boundary=RANDOM_STRING. If the beginning of the value is equal to `multipart/form-data`, it's a file upload and all of the `on_multipart_X()` callbacks will come into play. If it isn't multipart, proceed to step 2.

2) Check Transfer-Encoding header

If this header is set, the value may be `chunked` or another variation. However, if it is `chunked`, then the `on_chunk_X()` callbacks will be executed. If the header is not set, or the value is not `chunked`, proceed to step 3.

3) Transfer-Encoding header is not set

If it is not set, the format is URL encoded (looks like a query string, but is embedded into the body of the request). At this point it is safe to assume the `on_url_encoded_name()` and `on_url_encoded_value()` callbacks will be executed.

For proper examples, and I know they aren't a replacement for proper documentation at this time, but the `tests` directory has full tests/examples for chunked, multipart and URL encoded formats.

You may have other questions, feel free to ask them. I'll answer them as quickly as possible.

**Comment by serayuzgur** [comment]
Thanks for such a detailed answer (doc). I got it all 👍
